# Quiz 01

### Working with CIMIS Weather Station Data

Weather Data collected by CIMIS automatic weather stations. The data is available in CSV format. Station data include measured parameters such as solar radiation, air temperature, soil temperature, relative humidity, precipitation, wind speed and wind direction as well as derived parameters such as vapor pressure, dew point temperature, and grass reference evapotranspiration (ETo).

You are given 5 years of data for a few stations in Southern California. 

Create a new blank jupyter notebook. Follow the following sequence of instructions and answer questions accordingly. Upload the jupyter notebook directly into Brightspace.

1. Load the ```daily.csv``` dataset. You should know how to find where the file is located and specify the path to open it. 
2. How many unique stations are there in this dataset? 
3. Create a dataframe for each of the stations **individually** for the following fields: date, precipitation (```Precip (in)```), average air temperature (```Avg Air Temp (F)```) and average relative humidity (```Avg Rel Hum (%)```). You should have one dataframe per station with these four columns.
4. Calculate **average monthly** statistics for each of the weather variables at each station. i.e. you should have a dataframe with each month for each variable summarized by the mean of that variable over the past 5 years, mean precipitation for Januarys, for Februarys etc.
5. Write a few sentences describing differences you see between the stations and their 5-year climatologies. 
6. Create a function to convert degrees Farenheit to degrees Celsius. 
7. In each climatology dataframe convert  ```Avg Air Temp (F)``` to ```Avg Air Temp (C)``` and display results **rounded to one decimal place**.
8. For the **daily** data at the **Santa Monica** station, count the number of days in the five year dataset where ```Avg Air Temp (F)``` was below 50 degrees or above 100 degrees.

In [4]:
import pandas as pd
#import data
data = pd.read_csv('daily.csv')

In [5]:
#1
#view data
data.head(4000)
data.tail()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6573 entries, 0 to 6572
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Stn Id                6573 non-null   int64
 1   Stn Name              6573 non-null   object
 2   CIMIS Region          6573 non-null   object
 3   Date                  6573 non-null   object
 4   Jul                   6573 non-null   int64
 5   ETo (in)              6573 non-null   float64
 6   qc                    6573 non-null   object
 7   Precip (in)           6559 non-null   float64
 8   qc.1                  6573 non-null   object
 9   Sol Rad (Ly/day)      6558 non-null   float64
 10  qc.2                  6573 non-null   object
 11  Avg Vap Pres (mBars)  6556 non-null   float64
 12  qc.3                  6573 non-null   object
 13  Max Air Temp (F)      6408 non-null   float64
 14  qc.4                  6573 non-null   object
 15  Min Air Temp (F)      6523 non-null   float64
 16  qc.5                  6573 non-null   object
 17  Avg Air Temp (F)      6513 non-null   float64
 18  qc.6                  6573 non-null   object
 19  Max Rel Hum (%)       6558 non-null   float64
 20  qc.7                  6573 non-null   object
 21  Min Rel Hum (%)       6558 non-null   float64
 22  qc.8                  6573 non-null   object
 23  Avg Rel Hum (%)       6333 non-null   float64
 24  qc.9                  6573 non-null   object
 25  Dew Point (F)         6333 non-null   float64
 26  qc.10                 6573 non-null   object
 27  Avg Wind Speed (mph)  6559 non-null   float64
 28  qc.11                 6573 non-null   object
 29  Wind Run (miles)      6559 non-null   float64
 30  qc.12                 6573 non-null   object
 31  Avg Soil Temp (F)     6082 non-null   float64
 32  qc.13                 6573 non-null   object
dtypes: float64(14), int64(2), object(17)
memory usage: 1.7+ MB

In [6]:
print("there are 3 unique stations in this dataset: Station 44: UC Riverside, Station 99:, and Station 107: Santa Barbara")

there are 3 unique stations in this dataset: Station 44: UC Riverside, Station 99:, and Station 107: Santa Barbara

In [7]:
#3
#Create a dataframe for each of the stations individually for the following fields:
#Date, precip(in), avg air temp(F), and Avg Rel Hum (%).
#Station 44: UC Riverside
isolate = pd.DataFrame().assign(Station_Name=data['Stn Name'],
                                Date=data['Date'], 
                                  Precipitation=data['Precip (in)'],
                                  Avg_Air_Temp=data['Avg Air Temp (F)'],
                                  Avg_Rel_Humidity=data['Avg Rel Hum (%)'],)

print(isolate)

        Station_Name        Date  Precipitation  Avg_Air_Temp  \
0     U.C. Riverside    1/1/2017           0.00          47.8
1     U.C. Riverside    1/2/2017           0.00          49.6
2     U.C. Riverside    1/3/2017           0.00          47.8
3     U.C. Riverside    1/4/2017           0.00          50.8
4     U.C. Riverside    1/5/2017           0.13          55.2
...              ...         ...            ...           ...
6568   Santa Barbara  12/27/2022           0.82          55.2
6569   Santa Barbara  12/28/2022           0.00          54.4
6570   Santa Barbara  12/29/2022           0.03          54.6
6571   Santa Barbara  12/30/2022           0.02          54.8
6572   Santa Barbara  12/31/2022           2.11          55.9

      Avg_Rel_Humidity
0                 74.0
1                 75.0
2                 77.0
3                 73.0
4                 82.0
...                ...
6568              90.0
6569              87.0
6570              88.0
6571              98.0
6572              98.0

[6573 rows x 5 columns]

In [8]:
#Create data frame for each station
ucr = isolate[isolate['Station_Name']=='U.C. Riverside']
sb = isolate[isolate['Station_Name']=='Santa Barbara']
sm = isolate[isolate['Station_Name']=='Santa Monica']

In [9]:
print(ucr)

        Station_Name        Date  Precipitation  Avg_Air_Temp  \
0     U.C. Riverside    1/1/2017           0.00          47.8
1     U.C. Riverside    1/2/2017           0.00          49.6
2     U.C. Riverside    1/3/2017           0.00          47.8
3     U.C. Riverside    1/4/2017           0.00          50.8
4     U.C. Riverside    1/5/2017           0.13          55.2
...              ...         ...            ...           ...
2186  U.C. Riverside  12/27/2022           0.27          56.2
2187  U.C. Riverside  12/28/2022           0.06          53.5
2188  U.C. Riverside  12/29/2022           0.00          53.4
2189  U.C. Riverside  12/30/2022           0.02          53.9
2190  U.C. Riverside  12/31/2022           0.57          55.0

      Avg_Rel_Humidity
0                 74.0
1                 75.0
2                 77.0
3                 73.0
4                 82.0
...                ...
2186              60.0
2187              88.0
2188              84.0
2189              92.0
2190              97.0

[2191 rows x 5 columns]

In [10]:
print(sb)

       Station_Name        Date  Precipitation  Avg_Air_Temp  Avg_Rel_Humidity
4382  Santa Barbara    1/1/2017           0.00          45.3              70.0
4383  Santa Barbara    1/2/2017           0.00          46.4              80.0
4384  Santa Barbara    1/3/2017           0.00          49.0              74.0
4385  Santa Barbara    1/4/2017           0.00          46.7              91.0
4386  Santa Barbara    1/5/2017           0.00          44.1             100.0
...             ...         ...            ...           ...               ...
6568  Santa Barbara  12/27/2022           0.82          55.2              90.0
6569  Santa Barbara  12/28/2022           0.00          54.4              87.0
6570  Santa Barbara  12/29/2022           0.03          54.6              88.0
6571  Santa Barbara  12/30/2022           0.02          54.8              98.0
6572  Santa Barbara  12/31/2022           2.11          55.9              98.0

[2191 rows x 5 columns]

In [11]:
print(sm)

      Station_Name        Date  Precipitation  Avg_Air_Temp  Avg_Rel_Humidity
2191  Santa Monica    1/1/2017           0.00          49.7              75.0
2192  Santa Monica    1/2/2017           0.00          52.1              77.0
2193  Santa Monica    1/3/2017           0.00          52.7              75.0
2194  Santa Monica    1/4/2017           0.16          55.1              82.0
2195  Santa Monica    1/5/2017           0.49          56.1              96.0
...            ...         ...            ...           ...               ...
4377  Santa Monica  12/27/2022           0.41          57.8              70.0
4378  Santa Monica  12/28/2022           0.02          55.9              83.0
4379  Santa Monica  12/29/2022           0.00          55.7              82.0
4380  Santa Monica  12/30/2022           0.06          56.6              86.0
4381  Santa Monica  12/31/2022           1.17          56.8              94.0

[2191 rows x 5 columns]

In [12]:
#4 #NEED
#Calculate average monthly statistics for each of the weather variables at each station
#a dataframe with each month fo reach variable (mean precipitation for January, February, 
ucr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2191 entries, 0 to 2190
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Station_Name      2191 non-null   object
 1   Date              2191 non-null   object
 2   Precipitation     2191 non-null   float64
 3   Avg_Air_Temp      2191 non-null   float64
 4   Avg_Rel_Humidity  2178 non-null   float64
dtypes: float64(3), object(2)
memory usage: 102.7+ KB

#5. Write a few sentences describing differences you see between the stations and their 5-year climatologies. 

I cannot get my #4 to work, but based on the locations of the stations and scanning through t

In [21]:
#6 #GOOD
#Create a function that converts degrees Farenheit to degrees Celcius
def fahr_to_celsius(FarTemp):
    CelTemp = (FarTemp - 32)*5/9
    return CelTemp

In [38]:
#7 #Good
#For each climatology dataframe convert Avg Air Temp (F) to Avg Air Temp (C) display results rounded to one decimal place
def fahr_to_celsius(FarTemp):
    CelTemp = (FarTemp - 32)*5/9
    return CelTemp
ucr["Avg_Air_Temp_C"] = ucr["Avg_Air_Temp"].apply(fahr_to_celsius)
print(ucr)

        Station_Name        Date  Precipitation  Avg_Air_Temp  \
0     U.C. Riverside    1/1/2017           0.00          47.8
1     U.C. Riverside    1/2/2017           0.00          49.6
2     U.C. Riverside    1/3/2017           0.00          47.8
3     U.C. Riverside    1/4/2017           0.00          50.8
4     U.C. Riverside    1/5/2017           0.13          55.2
...              ...         ...            ...           ...
2186  U.C. Riverside  12/27/2022           0.27          56.2
2187  U.C. Riverside  12/28/2022           0.06          53.5
2188  U.C. Riverside  12/29/2022           0.00          53.4
2189  U.C. Riverside  12/30/2022           0.02          53.9
2190  U.C. Riverside  12/31/2022           0.57          55.0

      Avg_Rel_Humidity  Avg_Air_Temp_C
0                 74.0        8.777778
1                 75.0        9.777778
2                 77.0        8.777778
3                 73.0       10.444444
4                 82.0       12.888889
...                ...             ...
2186              60.0       13.444444
2187              88.0       11.944444
2188              84.0       11.888889
2189              92.0       12.166667
2190              97.0       12.777778

[2191 rows x 6 columns]

/tmp/ipykernel_79416/1057560092.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ucr["Avg_Air_Temp_C"] = ucr["Avg_Air_Temp"].apply(fahr_to_celsius)

In [41]:
ucr.round(decimals = 1)

,Station_Name,Date,Precipitation,Avg_Air_Temp,Avg_Rel_Humidity,Avg_Air_Temp_C
0,U.C. Riverside,1/1/2017,0.0,47.8,74.0,8.8
1,U.C. Riverside,1/2/2017,0.0,49.6,75.0,9.8
2,U.C. Riverside,1/3/2017,0.0,47.8,77.0,8.8
3,U.C. Riverside,1/4/2017,0.0,50.8,73.0,10.4
4,U.C. Riverside,1/5/2017,0.1,55.2,82.0,12.9
...,...,...,...,...,...,...
2186,U.C. Riverside,12/27/2022,0.3,56.2,60.0,13.4
2187,U.C. Riverside,12/28/2022,0.1,53.5,88.0,11.9
2188,U.C. Riverside,12/29/2022,0.0,53.4,84.0,11.9
2189,U.C. Riverside,12/30/2022,0.0,53.9,92.0,12.2
2190,U.C. Riverside,12/31/2022,0.6,55.0,97.0,12.8

In [35]:
#apply to the other data sets
def fahr_to_celsius(FarTemp):
    CelTemp = (FarTemp - 32)*5/9
    return CelTemp
sm["Avg_Air_Temp_C"] = sm["Avg_Air_Temp"].apply(fahr_to_celsius)
print(sm)

      Station_Name        Date  Precipitation  Avg_Air_Temp  Avg_Rel_Humidity  \
2191  Santa Monica    1/1/2017           0.00          49.7              75.0
2192  Santa Monica    1/2/2017           0.00          52.1              77.0
2193  Santa Monica    1/3/2017           0.00          52.7              75.0
2194  Santa Monica    1/4/2017           0.16          55.1              82.0
2195  Santa Monica    1/5/2017           0.49          56.1              96.0
...            ...         ...            ...           ...               ...
4377  Santa Monica  12/27/2022           0.41          57.8              70.0
4378  Santa Monica  12/28/2022           0.02          55.9              83.0
4379  Santa Monica  12/29/2022           0.00          55.7              82.0
4380  Santa Monica  12/30/2022           0.06          56.6              86.0
4381  Santa Monica  12/31/2022           1.17          56.8              94.0

      Avg_Air_Temp_C condition
2191        9.833333        No
2192       11.166667        No
2193       11.500000        No
2194       12.833333        No
2195       13.388889        No
...              ...       ...
4377       14.333333        No
4378       13.277778        No
4379       13.166667        No
4380       13.666667        No
4381       13.777778        No

[2191 rows x 7 columns]

/tmp/ipykernel_79416/3867627470.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sm["Avg_Air_Temp_C"] = sm["Avg_Air_Temp"].apply(fahr_to_celsius)

In [43]:
sm.round(decimals = 1)

,Station_Name,Date,Precipitation,Avg_Air_Temp,Avg_Rel_Humidity,Avg_Air_Temp_C
2191,Santa Monica,1/1/2017,0.0,49.7,75.0,9.8
2192,Santa Monica,1/2/2017,0.0,52.1,77.0,11.2
2193,Santa Monica,1/3/2017,0.0,52.7,75.0,11.5
2194,Santa Monica,1/4/2017,0.2,55.1,82.0,12.8
2195,Santa Monica,1/5/2017,0.5,56.1,96.0,13.4
...,...,...,...,...,...,...
4377,Santa Monica,12/27/2022,0.4,57.8,70.0,14.3
4378,Santa Monica,12/28/2022,0.0,55.9,83.0,13.3
4379,Santa Monica,12/29/2022,0.0,55.7,82.0,13.2
4380,Santa Monica,12/30/2022,0.1,56.6,86.0,13.7
4381,Santa Monica,12/31/2022,1.2,56.8,94.0,13.8

In [36]:
# apply to other data sets
def fahr_to_celsius(FarTemp):
    CelTemp = (FarTemp - 32)*5/9
    return CelTemp
sb["Avg_Air_Temp_C"] = sb["Avg_Air_Temp"].apply(fahr_to_celsius)
print(sb)

       Station_Name        Date  Precipitation  Avg_Air_Temp  \
4382  Santa Barbara    1/1/2017           0.00          45.3
4383  Santa Barbara    1/2/2017           0.00          46.4
4384  Santa Barbara    1/3/2017           0.00          49.0
4385  Santa Barbara    1/4/2017           0.00          46.7
4386  Santa Barbara    1/5/2017           0.00          44.1
...             ...         ...            ...           ...
6568  Santa Barbara  12/27/2022           0.82          55.2
6569  Santa Barbara  12/28/2022           0.00          54.4
6570  Santa Barbara  12/29/2022           0.03          54.6
6571  Santa Barbara  12/30/2022           0.02          54.8
6572  Santa Barbara  12/31/2022           2.11          55.9

      Avg_Rel_Humidity  Avg_Air_Temp_C
4382              70.0        7.388889
4383              80.0        8.000000
4384              74.0        9.444444
4385              91.0        8.166667
4386             100.0        6.722222
...                ...             ...
6568              90.0       12.888889
6569              87.0       12.444444
6570              88.0       12.555556
6571              98.0       12.666667
6572              98.0       13.277778

[2191 rows x 6 columns]

/tmp/ipykernel_79416/3313687689.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sb["Avg_Air_Temp_C"] = sb["Avg_Air_Temp"].apply(fahr_to_celsius)

In [44]:
sb1.round(decimals = 1)

,Station_Name,Date,Precipitation,Avg_Air_Temp,Avg_Rel_Humidity,Avg_Air_Temp_C
4382,Santa Barbara,1/1/2017,0.0,45.3,70.0,7.4
4383,Santa Barbara,1/2/2017,0.0,46.4,80.0,8.0
4384,Santa Barbara,1/3/2017,0.0,49.0,74.0,9.4
4385,Santa Barbara,1/4/2017,0.0,46.7,91.0,8.2
4386,Santa Barbara,1/5/2017,0.0,44.1,100.0,6.7
...,...,...,...,...,...,...
6568,Santa Barbara,12/27/2022,0.8,55.2,90.0,12.9
6569,Santa Barbara,12/28/2022,0.0,54.4,87.0,12.4
6570,Santa Barbara,12/29/2022,0.0,54.6,88.0,12.6
6571,Santa Barbara,12/30/2022,0.0,54.8,98.0,12.7
6572,Santa Barbara,12/31/2022,2.1,55.9,98.0,13.3

In [70]:
#8 #Good
#For the daily data at the santa monica station, count the nnumber of days in the five year dataset 
#where Avg Air Temp (F) was below 50 degrees or above 100
limit = 100
column_name = "Avg_Air_Temp"
# Select column 'C' from the dataframe
column = sm[column_name]
# Get count of values greater than 20 in the column 'C' 
count = column[column > limit].count()
print(count)

0

In [71]:
limit = 50
column_name = "Avg_Air_Temp"
# Select column 'C' from the dataframe
column = sm[column_name]
# Get count of values greater than 20 in the column 'C' 
count = column[column < limit].count()
print(count)

29

In [73]:
print("There are 29 days where air temp was below 50 or above 100 in santa monica")

There are 29 days where air temp was below 50 or above 100 in santa monica